services:
  stirling:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirling.rule=Host(`${FQDN_STIRLING:-stirling.test}`)"
      - "traefik.http.routers.stirling.entrypoints=websecure"
      - "traefik.http.routers.stirling.tls=true"
      - "traefik.http.services.stirling.loadbalancer.server.port=8080"

networks:
  default:
    name: ${NETWORK_NAME:-traefik-network}
    external: true
